apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:5zm2hOD7auNF0hZsYYhLfcOXEsxK6xuc8yz4oiBsxpC1PfixsyJg+++a+Iy6LoLtqVGZ2rqdaqCbGcj8AFJRcx8lxSlL4Fzr5UTfMpXsBgv8Xydl/x9d+wQ4//EfeLcaAwBgTpRPvIZbV+MRp4dU8bW0Z0d9ZuaczKUIb+xAt0HIXNHySupSzh+OddLEy3mfbF33WcTWMvYt9qJFreweWO5eX5AINHu+pYCwtlcxpsCDTbQqVpjGvSg6RWFYnNAvFzWYglKqupgr9zW9ORG2FwThZQ01+xDPWxEDC31d/J6z6ErhLQuVBxG8AzE=,iv:p4Wii7Ji5VtPSB6pw+zWtNUPzFp4swc/EqKjrkzNuvE=,tag:/JG/YjUmX+ZJ78+rBPvY2A==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age12ccuxm0z8n9zfqls0d64eewurc8shvfulh29eu4a6u76754tdqtsufslek
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dzJsZmZVWFBxRGo1UDN2
            Qmp1N0ZOSXpLazUyRlU3Z29jVjhZQnZKc2lnCjh4bmpVNGFxOWtNaHBCK29VdHBn
            SUo5cXZQRDI0S0libk9NYldvMi9XV0EKLS0tIDVNRG42TWNFR3hVbDZhTWZjcEVa
            MHFIbFRVcHVTYlBYWmo1L3lOclplRjgKm05n/AD5318hKfNmrMlXCVO7HKByYXde
            4yjCdFUBEWhrB+Eb27lPlkv1lPIxluJw0NC/uh7sx0p9J858owrlTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T15:51:23Z"
    mac: ENC[AES256_GCM,data:quHZOtvvY7TY/hOKXNsOK+v6HHJnUowj+2zmUwZQqvVfVKkBE/d9qdjE9vcSgM7HHyeImU1uxnSflZsHMfvL0B+Sfy2JqNWmB+cWZrHyQOPPD6XUQ6c8pNmdPz6fYslJDL1GsFr1Wh0BRSFZxSQyCgIFLz05/GwQxg2aWqEiNLQ=,iv:aDbcKS0sIwgkrbsD/Mv/0+07GYxJa40twH8LwHlk3Qk=,tag:WpKE1XZvo0AEn5XbJrrJTg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
